### ISSUE TITLE
bekomme die App nicht auf

### ISSUE THREAD

**Issue by ZephyrWk** [NiklasWyld/CutMate#1]
<img width="287" alt="image" src="https://github.com/NiklasWyld/CutMate/assets/99997210/09653973-1f3a-404d-a8ed-e603e03b68f8">

Grüße

**Comment by NiklasWyld** [comment]
Diese Meldung wird angezeigt, wenn eine App nicht bei Apple registriert ist. (Die App ist trotzdem sicher)
Einfach in den Systemeinstellungen unter Datenschutz & Sicherheit runterscrollen und auf "Dennoch öffnen" klicken.

<img width="819" alt="Bildschirmfoto 2023-12-26 um 14 50 19" src="https://github.com/NiklasWyld/CutMate/assets/84245129/cc4d12cb-4bb9-4c37-af7c-6f1b37f32dcf">
